name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.9.1

    - name: Install npm packages
      run: npm install

    - name: Install go packages
      run: go get

    - name: Build
      run: go run .

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: build
        folder: build/
